name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, ARM64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: dotnet restore InstantTraceViewer.sln

    - name: Publish MSIX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -m -target:Publish -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:NoWarn=1591 .\src\InstantTraceViewerMsixPackaging\InstantTraceViewerMsixPackaging.wapproj

    - name: Upload Instant Trace Viewer Unpackaged
      uses: actions/upload-artifact@v4
      with:
        name: InstantTraceViewer-${{ matrix.platform }}
        path: src/InstantTraceViewerMsixPackaging/bin/${{ matrix.platform }}/Release/InstantTraceViewerUI
        if-no-files-found: error

    - name: Upload Instant Trace Viewer MSIX
      uses: actions/upload-artifact@v4
      with:
        name: InstantTraceViewerMsix-${{ matrix.platform }}
        path: src/InstantTraceViewerMsixPackaging/bin/${{ matrix.platform }}/Release/Upload/InstantTraceViewerMsixPackaging_*
        if-no-files-found: error

    # The earlier step to publish only builds the MSIX package and its dependencies. This builds everything (like unit tests).
    - name: Build Everything
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -m -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:NoWarn=1591 InstantTraceViewer.sln

    # FIXME: ParseWinError excluded because C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared\winerror.h is not found on the build agent.
    - name: Run Unit Tests
      run: dotnet test src/UnitTests/UnitTests.csproj --configuration Release --filter "FullyQualifiedName!~ParseWinError"