name: Windows Build

on: [push, pull_request]
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, ARM64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore InstantTraceViewer.sln

    - name: Publish UI
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -m -target:Publish -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:NoWarn=1591 .\src\InstantTraceViewerUI\InstantTraceViewerUI.csproj

    - name: Upload Instant Trace Viewer
      uses: actions/upload-artifact@v3
      with:
        name: InstantTraceViewer-${{ matrix.platform }}
        path: src/InstantTraceViewerUI/bin/${{ matrix.platform }}/Release/net8.0-windows10.0.22621.0

    - name: Build Everything
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -m -target:Publish -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:NoWarn=1591 InstantTraceViewer.sln

    - name: Run Unit Tests
      run: dotnet test src/UnitTests/UnitTests.csproj --configuration Release
